const GEAR_PRODUCTS = [
  {
    id: 1,
    title: "Sleeping Bag (Down)",
    desc: "-5°C to -20°C",
    price: 150,
    oldPrice: 250,
    unit: "day",
    category: "gear",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Sleeping%20Bag%20(Down).jpg?updatedAt=1778251381303",
    rating: 4.8,
    badge: "Hot",
    badgeClass: "pb-hot"
  },
  {
    id: 2,
    title: "Sleeping Bag (Down)",
    desc: "-30°C to -40°C",
    price: 200,
    oldPrice: 300,
    unit: "day",
    category: "gear",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Sleeping%20Bag(Down).png?updatedAt=1778251390170",
    rating: 4.9,
    badge: "New",
    badgeClass: "pb-new"
  },
  {
    id: 3,
    title: "Down Jacket (Standard)",
    desc: "Cold protection jacket",
    price: 150,
    oldPrice: 200,
    unit: "day",
    category: "clothing",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Down%20Jacket%20(Standard).jpg?updatedAt=1778251378189",
    rating: 4.7
  },
  {
    id: 4,
    title: "High Altitude Tent",
    desc: "3+ days usage",
    price: 500,
    oldPrice: 750,
    unit: "day",
    category: "gear",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Tent.png?updatedAt=1778251384837",
    rating: 4.6,
    badge: "Sale",
    badgeClass: "pb-sale"
  },
  {
    id: 5,
    title: "Trekking Shoes (Normal)",
    desc: "Daily trekking shoes",
    price: 200,
    oldPrice: 350,
    unit: "day",
    category: "footwear",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Trekking%20Shoes%20(Normal).png?updatedAt=1778251387101",
    rating: 4.5
  },
  {
    id: 6,
    title: "Scarpa / La Sportiva",
    desc: "Premium mountaineering shoes",
    price: 4000,
    oldPrice: 5500,
    unit: "day",
    category: "footwear",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/La%20Sportiva.png?updatedAt=1778251382168",
    rating: 5.0,
    badge: "Premium",
    badgeClass: "pb-new"
  },
  {
    id: 7,
    title: "Backpack 50–60L",
    desc: "High altitude backpack",
    price: 250,
    oldPrice: 400,
    unit: "day",
    category: "bags",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Bagpack%2050-60L.jpg?updatedAt=1778251378106",
    rating: 4.8
  },
  {
    id: 8,
    title: "Trekking Pole",
    desc: "10–12 days day",
    price: 500,
    oldPrice: 700,
    unit: "day",
    category: "gear",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Trekking%20Poles.jpg?updatedAt=1778251381520",
    rating: 4.4
  },
  {
    id: 9,
    title: "Poncho",
    desc: "Waterproof rain protection",
    price: 30,
    oldPrice: 50,
    unit: "day",
    category: "clothing",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Poncho.png?updatedAt=1778251387773",
    rating: 4.2
  },
  {
    id: 10,
    title: "Hollofil jacket (unisex)",
    desc: "Synthetic insulation layer",
    price: 100,
    oldPrice: 180,
    unit: "day",
    category: "clothing",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/HollofilJacket.png",
    rating: 4.6
  },
  {
    id: 11,
    title: "Windproof Jacket",
    desc: "Lightweight wind protection",
    price: 70,
    oldPrice: 120,
    unit: "day",
    category: "clothing",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Windproof%20Jacket.png?updatedAt=1778251387898",
    rating: 4.7
  },
  {
    id: 12,
    title: "Flees Warm Jacket",
    desc: "Cozy fleece middle layer",
    price: 40,
    oldPrice: 80,
    unit: "day",
    category: "clothing",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Flees%20Warm%20Jacket.png?updatedAt=1778251387839",
    rating: 4.5
  },
  {
    id: 13,
    title: "Flees Cap",
    desc: "Head warmth for cold nights",
    price: 25,
    oldPrice: 45,
    unit: "day",
    category: "accessories",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Flees%20Cap.png?updatedAt=1778251385287",
    rating: 4.3
  },
  {
    id: 14,
    title: "Flees Gloves",
    desc: "Inner liner gloves",
    price: 15,
    oldPrice: 30,
    unit: "day",
    category: "clothing",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Flees%20Gloves.png?updatedAt=1778251387346",
    rating: 4.1
  },
  {
    id: 15,
    title: "Waterproof trekking gloves",
    desc: "Heavy-duty hand protection",
    price: 50,
    oldPrice: 90,
    unit: "day",
    category: "clothing",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Waterproof%20Trekking%20Gloves.png?updatedAt=1778251387070",
    rating: 4.8
  },
  {
    id: 16,
    title: "Head torch",
    desc: "Hands-free lighting",
    price: 25,
    oldPrice: 50,
    unit: "day",
    category: "accessories",
    image: "https://ik.imagekit.io/6krfkcqxh/Nepal_Himalaya/Product/Head%20Torch.png?updatedAt=1778251384819",
    rating: 4.4
  },
];
